### ISSUE TITLE
skrooge files are opened in read-only mode

### ISSUE THREAD

**Issue by VosaXalo** [flathub/org.kde.skrooge#1]
I have noted that when I open a file with skrooge, it's always in read-only mode.

Moreover, the path of the file is not as usual composed by my folders, but something strange like:
**/run/user/1000/doc/xxxx**
See the screenshot for an example:
![screenshot_20181128_194552](https://user-images.githubusercontent.com/6298140/49174428-9a7ddc00-f346-11e8-9d87-5867989e2684.png)

It's the same kind of issues that I have already posted here for the KeePassXC flatpak:
#https://github.com/flathub/org.keepassxc.KeePassXC/issues/26

**Comment by eszlari** [comment]
Try:
```
$ flatpak run --filesystem=host org.kde.skrooge
```

**Comment by VosaXalo** [comment]
I tried to use your command, but now there is another issue that prevent the app to start:

```
nicola@nicola-XPS-13-9360 ~> flatpak run --filesystem=host org.kde.skrooge
##WARNING: Qt: Session management error: Could not open network socket
##WARNING: KServiceTypeTrader: serviceType "ThumbCreator" not found
##FATAL: Cannot mix incompatible Qt library (version 0x50b02) with this library (version 0x50b03)
```

**Comment by mikeskid07** [comment]
I did not have the initial issue, but on a new system I have the same 2nd issue-> When opening from a menu Splashscreen loads, then nothing else happens. 
When opening from 'flatpak run org.kde.skrooge' I see basically the same error. (run w/ and w/o 'filesystem' flag.
Splashscreen briefly then terminal output of->
'##WARNING: KServiceTypeTrader: serviceType "ThumbCreator" not found
##FATAL: Cannot mix incompatible Qt library (version 0x50b02) with this library (version 0x50b03)'

Note that I do not in either circumstance (w/ flag or w/o) receive the line about 'QT: Session management error'

**Comment by eszlari** [comment]
A local build here works, so rebuilding against Qt 5.11.3 fixes this.

I opened a PR for the 2.17.0 update: https://github.com/flathub/org.kde.skrooge/pull/2

**Comment by bilelmoussaoui** [comment]
Sorry for the long delay. Totally missed this one. 

Does your PR @eszlari fix this issue?

**Comment by eszlari** [comment]
Yes, both.

**Comment by bilelmoussaoui** [comment]
Fixed. Thanks @eszlari

**Comment by VosaXalo** [comment]
Now it works perfectly.
Thank you very much!

**Comment by mikeskid07** [comment]
'tworks! Thanks!
