### ISSUE TITLE
Skrooge crashes again when opening, needs to be rebuilt

### ISSUE THREAD

**Issue by skierpage** [flathub/org.kde.skrooge#21]
The Qt runtime flatpak was recently updated, and once again the Skrooge stable flatpak stopped working. `flatpak run org.kde.skrooge/x86_64/master` fails with
 ```
##FATAL: Cannot mix incompatible Qt library (5.15.2) with this library (5.15.3)
```
This is the same issue as #7. As I understand it, KDE apps that use Qt plugins have to be rebuilt whenever the Qt runtime is recompiled ([KDE bug 408970](https://bugs.kde.org/show_bug.cgi?id=408970)). I think triggering a rebuild on flathub will fix it.

The Skrooge flatpak built from master on the kdeapps remote has the same problem.

**Comment by hfiguiere** [comment]
Triggered a new build: https://flathub.org/builds/#/builders/32/builds/44979

**Comment by hfiguiere** [comment]
And it failed because one of the module, `sqlcipher` can't be downloaded.

**Comment by tsdgeos** [comment]
Fixed now
