### ISSUE TITLE
nightly skrooge flatpak?

### ISSUE THREAD

**Issue by skierpage** [flathub/org.kde.skrooge#3]
Thanks so much for this, it lets me enjoy recent Skrooge fixes missing from the skrooge Fedora package. Latest Skrooge has even more fixes for bugs I reported, but it's difficult for me to test them. Is there a way to provide a special development or nightly flatpak? It seems development Flatpak builds aren't hosted on Flathub, [this suggests](https://community.kde.org/Guidelines_and_HOWTOs/Flatpak) nightly KDE flatpaks instead are at http://distribute.kde.org/kdeapps.flatpakrepo . I apologize if this is the wrong bug tracker for that.

**Comment by bilelmoussaoui** [comment]
Hey! Thanks for using Flatpak. 
Yes, flathub provide only stable releases (for now, it might change someday). I have tried to contact the devs about Flatpak & using the manifest I created. They are the ones that could ask to host a nightly release on the KDE nightly repository. 
If you ever reach them, please let them know about this repository.

**Comment by skierpage** [comment]
Hi @bilelmoussaoui , there's a [Phabricator project for Flatpak](https://phabricator.kde.org/project/profile/124/) and I think the master for the kdeapps repo is in [Diffusion](https://phabricator.kde.org/source/flatpak-kde-applications/repository/master/) , but I'm not sure where to file a bug or pull request to add a Skrooge flatpak.
