### ISSUE TITLE
 Skrooge fails to start due to Qt incompatibility

### ISSUE THREAD

**Issue by PecoraElettrica** [flathub/org.kde.skrooge#66]
Hii,
I've installed skrooge from scratch to a fresh system and I get this error
`Cannot mix incompatible Qt library (5.15.15) with this library (5.15.16)`

I think it's the same of #28 and connected.

**Comment by travier** [comment]
I've pushed the button to get a start a new build. Hopefully that will help.

**Comment by PecoraElettrica** [comment]
It probably isn't related to this build, since the date is 23 Nov, but I've updated from the extra-testing repo instead of extra and the version 2.33.0-4 is working, sorry for the hassle
