### ISSUE TITLE
Skrooge crashes when opening

### ISSUE THREAD

**Issue by VosaXalo** [flathub/org.kde.skrooge#7]
When I try to open skrooge, these messages are displayed:

```
➤ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=skrooge --file-forwarding org.kde.skrooge @@ %F @@
##WARNING: Qt: Session management error: Could not open network socket
##WARNING: KServiceTypeTrader: serviceType "ThumbCreator" not found
##FATAL: Cannot mix incompatible Qt library (version 0x50c01) with this library (version 0x50c02)
nicola@nicola-XPS-13-9360:~
```

I'm using KDE Neon 18.04 and flatpak 1.3.0

**Comment by skierpage** [comment]
This is happening for me too with a simple `flatpak run org.kde.skrooge` on Fedora 29. Maybe you have to be more precise in org.kde.skrooge.yml than just `base-version: '5.12'` (I assume 0x50c01 means Qt version 5.11.11). Or maybe a rebuild will fix this.

FWIW, if I run the Flathub app org.kde.elisa and choose [Hamburger] > About Elisa > Libraries, it displays "Qt 5.12.2 (built against 5.12.2)" and works fine. https://github.com/flathub/org.kde.elisa/blob/master/org.kde.elisa.json is different from org.kde.skrooge.yml: it doesn't specify `base-version: '5.12'` or `-DQt5WebKit_DIR` path.

**Comment by skierpage** [comment]
Skrooge was working for a while but recently the KDE runtime on Flathub updated to 5.12.4, and now I'm getting the same version mismatch error:
```
##FATAL: Cannot mix incompatible Qt library (version 0x50c03) with this library (version 0x50c04)
```
It's unfortunate that a difference in the patch level of Qt breaks this app. I think rebuilding it should fix this. `flatpak info org.kde.Platform` and `flatpak info org.kde.skrooge/x86_64/master` shows the platform commit date is June 19th (commit subject "Update to Qt 5.12.4"; while the skrooge commit subject and date is "Built on Mon Jun 17". I don't know if there's an automated way to get all KDE apps with this "incompatible Qt library" issue to be rebuilt whenever the runtime flatpak is rebuilt with a different Qt version.

(The build from master of skrooge on kdeapps has the same error, I filed [KDE bug 408970] (https://bugs.kde.org/show_bug.cgi?id=408970).

**Comment by TingPing** [comment]
Here is a new build: https://flathub.org/builds/#/builders/32/builds/4777

**Comment by skierpage** [comment]
For future reference, because Skrooge uses Qt plug-ins it must be rebuilt against the same libraries as the the KDE platform runtime flatpak whenever the latter changes to a different Qt version (e.g. 5.12.4) otherwise it fails to run with this "Cannot mix incompatible Qt library".

> Here is a new build: https://flathub.org/builds/#/builders/32/builds/4777

Thanks! That failed in appdata.xml validation. I filed [KDE bug 409026](https://bugs.kde.org/show_bug.cgi?id=409026) and submitted [Differential revision D21984](https://phabricator.kde.org/D21984).

**Comment by nedrichards** [comment]
Should be fixed by https://github.com/flathub/org.kde.skrooge/commit/2f1061f61dbc638b43f4e0077c52d3ba2d28ed4f
